name: Docs request
description: Request documentation improvements.
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: textarea
    id: docs
    attributes:
      label: What should be documented?
    validations:
      required: true
  - type: textarea
    id: audience
    attributes:
      label: Who is the audience?
